public class ActivateNotificationPanel : SingletonMonoBehaviour
{
	public SpriteText messageText;

	public static ActivateNotificationPanel Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<ActivateNotificationPanel>();
		}
	}

	public string Message
	{
		set
		{
			messageText.Text = value;
		}
	}

	public static ActivateNotificationPanel GetOrCreateInstance()
	{
		return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<ActivateNotificationPanel>();
	}

	protected override void AwakeOnce()
	{
		base.AwakeOnce();
	}

	public void SetHidden(bool isHidden)
	{
		base.gameObject.SetActive(!isHidden);
	}
}
