public class BountyNotificationPanel : SingletonMonoBehaviour
{
	public PrefabPlaceholder bountyBarPlaceholder;

	public SoundEventData bountyCompleteSound;

	private BountyBar _bountyBarInstance;

	public static BountyNotificationPanel Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<BountyNotificationPanel>();
		}
	}

	public Bounty Bounty
	{
		set
		{
			_bountyBarInstance.Bounty = value;
		}
	}

	public static BountyNotificationPanel GetOrCreateInstance()
	{
		return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<BountyNotificationPanel>();
	}

	protected override void AwakeOnce()
	{
		_bountyBarInstance = bountyBarPlaceholder.InstantiatePrefab().GetComponent<BountyBar>();
		_bountyBarInstance._button.GetComponent<UnityEngine.Collider>().enabled = false;
		_bountyBarInstance._button.controlIsEnabled = false;
	}

	public void SetHidden(bool isHidden)
	{
		_bountyBarInstance.gameObject.SetActive(!isHidden);
		_bountyBarInstance._button.GetComponent<UnityEngine.Collider>().enabled = false;
		_bountyBarInstance._button.controlIsEnabled = false;
	}
}
