public class CollectionNotificationPanel : SingletonMonoBehaviour
{
	public SpriteText messageText;

	public static CollectionNotificationPanel Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<CollectionNotificationPanel>();
		}
	}

	public string Message
	{
		set
		{
			messageText.Text = value;
		}
	}

	public static CollectionNotificationPanel GetOrCreateInstance()
	{
		return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<CollectionNotificationPanel>();
	}

	protected override void AwakeOnce()
	{
		base.AwakeOnce();
	}

	public void SetHidden(bool isHidden)
	{
		base.gameObject.SetActive(!isHidden);
	}
}
