public class PurchaseNotificationPanel : SingletonMonoBehaviour
{
	public SpriteText messageText;

	public static PurchaseNotificationPanel Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<PurchaseNotificationPanel>();
		}
	}

	public string Message
	{
		set
		{
			messageText.Text = value;
		}
	}

	public static PurchaseNotificationPanel GetOrCreateInstance()
	{
		return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<PurchaseNotificationPanel>();
	}

	protected override void AwakeOnce()
	{
		base.AwakeOnce();
	}

	public void SetHidden(bool isHidden)
	{
		base.gameObject.SetActive(!isHidden);
	}
}
